<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <!-- 指定父项目为 origin-springboot -->
    <parent>
        <groupId>com.cosmos</groupId>
        <artifactId>origin-springboot</artifactId>
        <version>${revision}</version>
    </parent>

    <!-- 多模块项目需要配置打包方式为 pom -->
    <packaging>pom</packaging>

    <artifactId>origin-admin</artifactId>
    <name>${project.artifactId}</name>
    <description>管理后台聚合模块</description>

    <modules>
        <!-- 管理后台 API 接口定义 -->
        <module>origin-admin-api</module>
        <!-- 管理后台业务逻辑（无 Controller，可被单体/微服务复用） -->
        <module>origin-admin-logic</module>
        <!-- 管理后台业务实现（Controller 层） -->
        <module>origin-admin-biz</module>
    </modules>

</project>
